### ISSUE TITLE
Not entirely clear on onFileUpload return values

### ISSUE THREAD

**Issue by joendres** [thundernest/webext-docs#13]
Regarding onFileUpload's return values [the docs say](https://github.com/thundernest/webext-docs/blob/68/cloudFile.rst#onfileuploadaccount-fileinfo):
```
  - [``aborted``] (boolean) Set this to true if the file upload was aborted
```
Does this mean "... if the upload was aborted..."
1. ... by ```onFileUploadAbort```
1. ... for any *other* reason, eg network failure or timeout
1. ... for any reason (inluding ```onFileUploadAbort)```

**Comment by jobisoft** [comment]
Returning `aborted: true` will not show any error to the user, because it is assumed to have been aborted by the user. If you encounter errors on the server side, you can use the new `error` property to show an error to the user.

https://webextension-api.thunderbird.net/en/latest/cloudFile.html#onfileupload

But I will update the documentation and add this info.

**Comment by jobisoft** [comment]
![grafik](https://user-images.githubusercontent.com/5830621/152656154-85b17f49-ba7c-45d8-a4b5-69f7dc18976b.png)

Screenshot from 
https://webextension-api.thunderbird.net/en/latest/cloudFile.html#onfileupload

Good?

**Comment by joendres** [comment]
Could we clarify the explanation of ```aborted``` to "...was aborted by the user. No error..." ?
